FROM ubuntu:16.04
MAINTAINER fpwanderley@gmail.com
# ##############################################################

ENV RUNTIME_PACKAGES software-properties-common vim
ENV RUNTIME_PACKAGES_2 python3.6 python3-pip
#ENV RUNTIME_PACKAGES_2 python3.6 python3-pip ipython3 python3-venv

RUN apt-get update
RUN apt-get install -y $RUNTIME_PACKAGES && apt-get clean

RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update
RUN apt-get install -y $RUNTIME_PACKAGES_2
RUN pip3 install --upgrade pip
RUN echo 'alias python="python3.6"' >> ~/.bashrc


