FROM infome-dev:1.0
MAINTAINER fpwanderley@gmail.com
# ##############################################################
ENV EXTRA_PYTHON_PACKAGES Django==1.11.4 ipython

# # ##############################################################
RUN python3.6 -m pip install $EXTRA_PYTHON_PACKAGES

CMD chmod +x InfoMe/start_server.sh && \
    InfoMe/start_server.sh  && \
    /bin/bash
